#/////////////////////////////////////////////////////////////////////////////////////////////////////////////
#' Both Connecticut and Alaska had changes on county FIPS in/after 2019 
#' The county travel networks need to be converted to match modern jurisdictions
#' https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.January_2020.html
#' The January 2020 tab can be cited for the Connecticut change and 2010 for Alaska
#' 
#' Crosswalk from GeoCorr 2022: https://mcdc.missouri.edu/applications/geocorr2022.html
#' 
#' Parent dir: MOBILITY
#/////////////////////////////////////////////////////////////////////////////////////////////////////////////

final_crosswalk = "../data/MOBILITY/ak_ct_crosswalk.csv"
if(!file.exists(final_crosswalk)){
  #//////////////////////////////
  #### CONNECTICUT CROSSWALK ####
  # Planning Regions are the new county-like units of Connecticut after 2023
  # 2020 Population weighted allocation factor of new planning region to county
  
  source("../data/private_input_data/api_keys.R")
  
  ct_crosswalk = read_csv("../data/MOBILITY/connecticut_county_crosswalk_geocorr2022.csv") %>% 
    rename(
      OLD_FIPS = CTcounty, # County code
      NEW_FIPS = county,    # Connecticut planning region
      NEW_Name = CountyName, # Plannning Region name post-2023 change
      OLD_Name = CTCountyName, # CT county name pre-2023
      POP_2020 = pop20 # 2020 census population
    )
  ct_crosswalk = ct_crosswalk[-1,] # row 1 of file is description row
  
  #/////////////////////////
  #### ALASKA CROSSWALK ####
  # Crosswalk generated by hand
  # 2019 ACS 5-year
  ak_pop_2019 <- tidycensus::get_acs(
    geography = "county",
    state = "AK",
    year = 2019,
    survey = "acs5",
    variables = "B01001_001") %>%
    dplyr::filter(GEOID=="02261") %>%
    rename(
      OLD_FIPS = GEOID,
      OLD_Name = NAME ) %>%
    dplyr::select(OLD_FIPS, OLD_Name)
  
  # 2020 ACS 5-year
  ak_pop_2020 <- tidycensus::get_acs(
    geography = "county",
    state = "AK",
    year = 2020,
    survey = "acs5",
    variables = "B01001_001") %>%
    dplyr::filter(GEOID %in% c("02063", "02066")) %>%
    mutate(
      POP_SUM = 9389, # sum(estimate)
      afact = round(estimate/POP_SUM, 2)) %>% # proportion of population (allocation factor)
    rename(
      NEW_FIPS = GEOID,    
      NEW_Name = NAME, 
      POP_2020 = estimate ) %>%
    dplyr::select(-moe, -variable, -POP_SUM) %>%
    cross_join(ak_pop_2019)
  
  #///////////////////////
  #### FULL CROSSWALK ####
  ak_ct_crosswalk = ak_pop_2020 %>%
    bind_rows(ct_crosswalk %>% type_convert())
  
  write.csv(ak_ct_crosswalk,
            final_crosswalk,
            row.names = F)
}else{
  print("AK + CT crosswalk alredy exists")
} # end if the crosswalk needs to be made










