#////////
#### Section 6f Selected Local Scenario Runner ####
#////////
#' Run selected generated scenarios locally for dashboard preview.
#'
#' Inputs:
#'   - PIPELINE_OUTPUT_DIR/TACC_FILES generated by 6d
#'   - SELECTED_RUN_STATES, e.g. c("District-of-Columbia", "Connecticut")
#'   - SELECTED_RUN_SCENARIOS, e.g. c("BASELINE", "VACCINE")
#'
#' Outputs:
#'   - PIPELINE_OUTPUT_DIR/WEB_INPUTS/*.json
#'   - PIPELINE_OUTPUT_DIR/WEB_INPUTS/web_state_commands.sh
#'   - PIPELINE_OUTPUT_DIR/WEB_OUTPUTS/*
#'
#' When sourced from 0_run_full_pipeline_US.R, shell output is streamed through
#' run_logged_command(), so it prints to the console and appends to the pipeline log.

#////////
#### Section 6f Package Setup ####
#////////
library(tidyverse)
library(jsonlite)

#////////
#### Section 6f Arguments ####
#////////
get_arg_value_6f <- function(prefix, default) {
  args <- commandArgs(trailingOnly = TRUE)
  match <- args[startsWith(args, prefix)]
  if (length(match) == 0) return(default)
  sub(prefix, "", match[[1]], fixed = TRUE)
}

split_arg_6f <- function(value, default) {
  if (is.null(value) || length(value) == 0 || !nzchar(value)) return(default)
  pieces <- trimws(unlist(strsplit(value, ",", fixed = TRUE)))
  pieces[nzchar(pieces)]
}

PIPELINE_OUTPUT_DIR <- get0(
  "PIPELINE_OUTPUT_DIR",
  ifnotfound = get_arg_value_6f("--output-dir=", "STATE_MANUSCRIPT_TEST")
)
SIMULATION_DAYS <- as.integer(get0(
  "SIMULATION_DAYS",
  ifnotfound = get_arg_value_6f("--simulation-days=", "300")
))
SELECTED_RUN_STATES <- get0(
  "SELECTED_RUN_STATES",
  ifnotfound = split_arg_6f(
    get_arg_value_6f("--selected-states=", ""),
    c("District-of-Columbia", "Connecticut", "Massachusetts")
  )
)
INTERVENTION_TEMPLATE_FILES <- get0("INTERVENTION_TEMPLATE_FILES", ifnotfound = character())
SELECTED_RUN_SCENARIOS <- get0(
  "SELECTED_RUN_SCENARIOS",
  ifnotfound = split_arg_6f(
    get_arg_value_6f("--selected-scenarios=", ""),
    c("BASELINE", names(INTERVENTION_TEMPLATE_FILES))
  )
)
SIM_DAY_0_VALUES <- as.character(get0("SIM_DAY_0_VALUES", ifnotfound = character()))

expected_sim_day_0_6f <- function(input_json) {
  config <- jsonlite::fromJSON(input_json, simplifyVector = FALSE)
  sim_day_0 <- tryCatch(config$metadata_tags$sim_day_0, error = function(e) NA_character_)
  if (is.null(sim_day_0)) sim_day_0 <- NA_character_
  as.character(sim_day_0)
}

metadata_tag_chr_6f <- function(config, tag_name) {
  value <- tryCatch(config$metadata_tags[[tag_name]], error = function(e) NA_character_)
  if (is.null(value)) NA_character_ else as.character(value)
}

#////////
#### Section 6f Paths ####
#////////
input_dir <- file.path("..", PIPELINE_OUTPUT_DIR, "TACC_FILES")
selected_input_dir <- file.path("..", PIPELINE_OUTPUT_DIR, "WEB_INPUTS")
selected_output_dir <- file.path("..", PIPELINE_OUTPUT_DIR, "WEB_OUTPUTS")
selected_commands_file <- file.path(selected_input_dir, "web_state_commands.sh")
simulator_file_rel_from_web_outputs <- file.path("..", "..", "src", "simulator.py")

dir.create(selected_input_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(selected_output_dir, recursive = TRUE, showWarnings = FALSE)
selected_input_dir_abs <- normalizePath(selected_input_dir, mustWork = TRUE)
selected_output_dir_abs <- normalizePath(selected_output_dir, mustWork = TRUE)
if (length(SIM_DAY_0_VALUES) == 0) {
  SIM_DAY_0_VALUES <- list.dirs(input_dir, recursive = FALSE, full.names = FALSE)
}

cat("Selected local simulator states: ", paste(SELECTED_RUN_STATES, collapse = ", "), "\n", sep = "")
cat("Selected local simulator scenarios: ", paste(SELECTED_RUN_SCENARIOS, collapse = ", "), "\n", sep = "")

#////////
#### Section 6f Selected Inputs ####
#////////
generated_input_files <- list.files(
  input_dir,
  pattern = "^INPUT_.*\\.json$",
  full.names = TRUE,
  recursive = TRUE
)
if (length(generated_input_files) == 0) {
  stop("No generated input JSONs found in ", input_dir, ". Run 6d first.")
}

selected_inputs <- tibble(source_file = generated_input_files) %>%
  mutate(
    config = purrr::map(.data$source_file, jsonlite::fromJSON, simplifyVector = FALSE),
    state = purrr::map_chr(.data$config, metadata_tag_chr_6f, "state_dir"),
    sim_day_0 = purrr::map_chr(.data$config, metadata_tag_chr_6f, "sim_day_0"),
    scenario = purrr::map_chr(.data$config, metadata_tag_chr_6f, "scenario_label")
  ) %>%
  dplyr::filter(
    .data$state %in% SELECTED_RUN_STATES,
    .data$sim_day_0 %in% SIM_DAY_0_VALUES,
    .data$scenario %in% SELECTED_RUN_SCENARIOS
  ) %>%
  mutate(
    state_order = match(.data$state, SELECTED_RUN_STATES),
    date_order = match(.data$sim_day_0, SIM_DAY_0_VALUES),
    scenario_order = match(.data$scenario, SELECTED_RUN_SCENARIOS)
  ) %>%
  arrange(.data$state_order, .data$date_order, .data$scenario_order) %>%
  select(-config, -state_order, -date_order, -scenario_order)

expected_selected_inputs <- tidyr::expand_grid(
  state = SELECTED_RUN_STATES,
  sim_day_0 = SIM_DAY_0_VALUES,
  scenario = SELECTED_RUN_SCENARIOS
)
missing_selected_inputs <- expected_selected_inputs %>%
  anti_join(selected_inputs, by = c("state", "sim_day_0", "scenario"))
if (nrow(missing_selected_inputs) > 0) {
  stop(
    "Missing generated input JSON(s) for selected combinations: ",
    paste(
      paste(missing_selected_inputs$state, missing_selected_inputs$sim_day_0, missing_selected_inputs$scenario, sep = " | "),
      collapse = ", "
    )
  )
}

selected_inputs <- selected_inputs %>%
  mutate(
    source_stem = tools::file_path_sans_ext(basename(.data$source_file)),
    expected_sim_day_0 = purrr::map_chr(.data$source_file, expected_sim_day_0_6f),
    selected_file = file.path(selected_input_dir, .data$expected_sim_day_0, basename(.data$source_file)),
    selected_command_input = file.path(selected_input_dir_abs, .data$expected_sim_day_0, basename(.data$source_file))
  )

#////////
#### Section 6f Write Selected JSONs ####
#////////
repo_relative_from_web_outputs_6f <- function(path) {
  if (is.null(path) || !nzchar(path)) return(path)
  repo_root <- normalizePath("..", mustWork = TRUE)
  path_abs <- if (grepl("^/", path)) {
    normalizePath(path, mustWork = FALSE)
  } else {
    normalizePath(file.path(selected_output_dir_abs, path), mustWork = FALSE)
  }
  repo_prefix <- paste0(repo_root, .Platform$file.sep)
  if (startsWith(path_abs, repo_prefix)) {
    return(file.path("..", "..", sub(repo_prefix, "", path_abs, fixed = TRUE)))
  }
  path
}

relativize_data_paths_6f <- function(config) {
  if (is.null(config$data)) return(config)
  for (data_name in intersect(names(config$data), c("population", "contact", "flow", "high_risk_ratios"))) {
    config$data[[data_name]] <- repo_relative_from_web_outputs_6f(config$data[[data_name]])
  }
  config
}

purrr::pwalk(
  selected_inputs,
  function(state, sim_day_0, scenario, source_file, selected_file, selected_command_input, ...) {
    config <- jsonlite::fromJSON(source_file, simplifyVector = FALSE)
    config <- relativize_data_paths_6f(config)
    config$output_dir_path <- "GENERATE"
    config$batch_num <- "GENERATE"
    dir.create(dirname(selected_file), recursive = TRUE, showWarnings = FALSE)
    jsonlite::write_json(config, selected_file, auto_unbox = TRUE, pretty = TRUE, null = "null")
  }
)

#////////
#### Section 6f Existing Output Check ####
#////////
expected_sim_ids_6f <- function(input_json) {
  config <- jsonlite::fromJSON(input_json, simplifyVector = FALSE)
  realization_range <- as.integer(unlist(config$realization_range))
  if (length(realization_range) != 2 || any(is.na(realization_range))) {
    stop("Input JSON does not have a valid two-value realization_range: ", input_json)
  }
  seq.int(realization_range[[1]], realization_range[[2]])
}

input_json_matches_6f <- function(existing_input_file, expected_input_file) {
  if (!file.exists(existing_input_file) || !file.exists(expected_input_file)) {
    return(FALSE)
  }
  existing_config <- tryCatch(
    jsonlite::fromJSON(existing_input_file, simplifyVector = FALSE),
    error = function(e) NULL
  )
  expected_config <- tryCatch(
    jsonlite::fromJSON(expected_input_file, simplifyVector = FALSE),
    error = function(e) NULL
  )
  identical(existing_config, expected_config)
}

metadata_batch_status_6f <- function(metadata_file, state, scenario, expected_ids,
                                     expected_sim_day_0, expected_simulation_days,
                                     expected_input_file) {
  metadata <- tryCatch(
    jsonlite::fromJSON(metadata_file, simplifyVector = FALSE),
    error = function(e) NULL
  )
  if (is.null(metadata)) return(NULL)

  metadata_state <- metadata_tag_chr_6f(metadata, "state_dir")
  metadata_sim_day_0 <- tryCatch(metadata$metadata_tags$sim_day_0, error = function(e) NA_character_)
  metadata_simulation_days <- suppressWarnings(as.integer(tryCatch(metadata$cli_args$days, error = function(e) NA_integer_)))
  metadata_scenario <- metadata_tag_chr_6f(metadata, "scenario_label")

  batch_num <- tryCatch(metadata$batch_num, error = function(e) NA_character_)
  existing_input_file <- file.path(dirname(metadata_file), paste0("input_batch-", batch_num, ".json"))
  input_matches <- input_json_matches_6f(existing_input_file, expected_input_file)

  matches_selection <- identical(as.character(metadata_state), as.character(state)) &&
    identical(as.character(metadata_scenario), as.character(scenario)) &&
    identical(as.character(metadata_sim_day_0), as.character(expected_sim_day_0)) &&
    identical(metadata_simulation_days, as.integer(expected_simulation_days)) &&
    isTRUE(input_matches)

  if (!matches_selection) return(NULL)

  sim_file <- file.path(dirname(metadata_file), paste0("simulation_times_batch-", batch_num, ".csv"))
  sim_ids <- integer(0)
  if (file.exists(sim_file)) {
    timing_data <- tryCatch(
      utils::read.csv(sim_file, check.names = FALSE),
      error = function(e) data.frame(sim_id = integer())
    )
    sim_ids <- sort(unique(as.integer(timing_data$sim_id)))
  }

  list(
    output_dir = dirname(metadata_file),
    scenario_hash = tryCatch(metadata$scenario_hash, error = function(e) NA_character_),
    batch_num = batch_num,
    complete = identical(sim_ids, expected_ids),
    completed = length(intersect(sim_ids, expected_ids)),
    expected = length(expected_ids),
    missing = setdiff(expected_ids, sim_ids),
    extra = setdiff(sim_ids, expected_ids),
    metadata_reason = paste0(
      "metadata sim_day_0=", as.character(metadata_sim_day_0),
      " days=", metadata_simulation_days,
      " batch=", as.character(batch_num),
      " input_config_match=", input_matches
    )
  )
}

selected_output_status_6f <- function(output_root, state, scenario, expected_ids,
                                      expected_sim_day_0, expected_simulation_days,
                                      expected_input_file) {
  metadata_files <- list.files(
    output_root,
    pattern = "^metadata_batch-.*\\.json$",
    recursive = TRUE,
    full.names = TRUE
  )
  batch_statuses <- purrr::compact(purrr::map(
    metadata_files,
    metadata_batch_status_6f,
    state = state,
    scenario = scenario,
    expected_ids = expected_ids,
    expected_sim_day_0 = expected_sim_day_0,
    expected_simulation_days = expected_simulation_days,
    expected_input_file = expected_input_file
  ))

  if (length(batch_statuses) == 0) {
    return(list(
      complete = FALSE,
      exists = FALSE,
      completed = 0L,
      expected = length(expected_ids),
      missing = expected_ids,
      extra = integer(0),
      output_dir = NA_character_,
      scenario_hash = NA_character_,
      batch_num = NA_character_,
      metadata_reason = "no matching generated metadata/input config"
    ))
  }

  complete_statuses <- purrr::keep(batch_statuses, ~ isTRUE(.x$complete))
  if (length(complete_statuses) > 0) {
    complete_statuses[[1]]$exists <- TRUE
    return(complete_statuses[[1]])
  }

  batch_statuses[[1]]$exists <- TRUE
  batch_statuses[[1]]
}

cat("\nChecking selected local scenario outputs before running simulator commands...\n")
selected_inputs$expected_sim_ids <- purrr::map(selected_inputs$selected_file, expected_sim_ids_6f)
selected_inputs$output_status <- purrr::pmap(
  list(
    selected_inputs$state,
    selected_inputs$scenario,
    selected_inputs$expected_sim_ids,
    selected_inputs$expected_sim_day_0,
    selected_inputs$selected_file
  ),
  function(state, scenario, expected_sim_ids, expected_sim_day_0, selected_file) {
    selected_output_status_6f(
      selected_output_dir,
      state,
      scenario,
      expected_sim_ids,
      expected_sim_day_0,
      SIMULATION_DAYS,
      selected_file
    )
  }
)

selected_inputs <- selected_inputs %>%
  mutate(
    output_complete = purrr::map_lgl(.data$output_status, "complete"),
    output_exists = purrr::map_lgl(.data$output_status, "exists"),
    completed_sims = purrr::map_int(.data$output_status, "completed"),
    expected_sims = purrr::map_int(.data$output_status, "expected"),
    scenario_hash = purrr::map_chr(.data$output_status, "scenario_hash"),
    output_dir = purrr::map_chr(.data$output_status, "output_dir"),
    batch_num = purrr::map_chr(.data$output_status, "batch_num"),
    metadata_reason = purrr::map_chr(.data$output_status, "metadata_reason")
  )

purrr::pwalk(
  selected_inputs,
  function(state, sim_day_0, scenario, source_file, source_stem, expected_sim_day_0, selected_file,
           selected_command_input, expected_sim_ids, output_status, output_complete, output_exists,
           completed_sims, expected_sims, scenario_hash, output_dir, batch_num, metadata_reason) {
    label <- paste(state, scenario)
    if (isTRUE(output_complete)) {
      cat("  SKIP complete selected scenario ", label, ": sims ",
          min(expected_sim_ids), "-", max(expected_sim_ids),
          " present (", completed_sims, "/", expected_sims,
          "), sim_day_0 ", expected_sim_day_0,
          ", days ", SIMULATION_DAYS,
          ", hash ", substr(scenario_hash, 1, 8),
          ", batch ", batch_num, ".\n", sep = "")
      return(invisible(NULL))
    }

    if (isTRUE(output_exists)) {
      missing_preview <- paste(head(output_status$missing, 10), collapse = ",")
      if (length(output_status$missing) > 10) missing_preview <- paste0(missing_preview, ",...")
      cat("  RUN selected scenario ", label, ": matching hash output is incomplete; sims ",
          completed_sims, "/", expected_sims,
          " present; missing ", missing_preview,
          "; ", metadata_reason,
          ". Keeping existing files.\n", sep = "")
    } else {
      cat("  RUN missing selected scenario ", label,
          ": no complete output found for this generated input JSON, sim_day_0 ",
          expected_sim_day_0, ", days ", SIMULATION_DAYS,
          ".\n", sep = "")
    }
    invisible(NULL)
  }
)

selected_inputs_to_run <- selected_inputs %>%
  dplyr::filter(!.data$output_complete)

#////////
#### Section 6f Run Selected Commands ####
#////////
selected_commands <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  'cd "$(dirname "$0")/../../scripts"',
  unlist(purrr::pmap(
    selected_inputs_to_run,
    function(state, sim_day_0, scenario, source_file, source_stem, expected_sim_day_0, selected_file,
             selected_command_input, expected_sim_ids, output_status, output_complete, output_exists,
             completed_sims, expected_sims, scenario_hash, output_dir, batch_num, metadata_reason) {
      c(
        paste0("# sim_day_0=", expected_sim_day_0, " state=", state, " scenario=", scenario),
        paste0("echo 'START sim_day_0=", expected_sim_day_0, " state=", state, " scenario=", scenario, " at '$(date '+%Y-%m-%d %H:%M:%S')"),
        paste(
          "(cd",
          shQuote(selected_output_dir_abs),
          "&& mkdir -p GENERATE",
          "&& set +e",
          "&& poetry run python3",
          shQuote(simulator_file_rel_from_web_outputs),
          "-l INFO -d",
          SIMULATION_DAYS,
          "-i",
          shQuote(file.path("..", "WEB_INPUTS", expected_sim_day_0, basename(selected_command_input))),
          "; status=$?",
          "; rmdir GENERATE 2>/dev/null || true",
          "; exit $status",
          ")"
        ),
        paste0("echo 'DONE sim_day_0=", expected_sim_day_0, " state=", state, " scenario=", scenario, " at '$(date '+%Y-%m-%d %H:%M:%S')")
      )
    }
  ))
)

writeLines(selected_commands, selected_commands_file)
Sys.chmod(selected_commands_file, mode = "0755")
cat("Wrote ", nrow(selected_inputs_to_run), " selected simulator commands to ", selected_commands_file, "\n", sep = "")

if (nrow(selected_inputs_to_run) == 0) {
  cat("All selected local scenarios already have complete simulation_times and matching metadata; no simulator commands to run.\n")
  selected_status <- 0L
} else {
  if (exists("run_logged_command", mode = "function")) {
    selected_status <- run_logged_command("bash", selected_commands_file)
  } else {
    selected_status <- system2("bash", selected_commands_file)
  }
}

if (!identical(selected_status, 0L)) {
  stop("Selected simulator commands failed with exit status ", selected_status)
}
